import type { ReminderType } from "@pawcareright/types";

import type { ScheduleFrequency } from "./reminders/schedule-builder";

// Centralized user-facing copy for apps/mobile (CLAUDE.md §6).
// The product display name is never hardcoded here — it is injected at
// render time from the shared `APP_DISPLAY_NAME` constant.

// Care-scheduling labels only (T058 plan Safety statement) -- no medical
// advice, no diagnosis language.
const NOTIFICATION_TYPE_LABELS: Record<ReminderType, string> = {
  VACCINE: "Vaccines",
  PARASITE: "Parasite prevention",
  MEDICATION: "Medications",
  GROOMING: "Grooming",
  DENTAL: "Dental care",
  VET_VISIT: "Vet visits",
  CUSTOM: "Custom reminders",
};

/** `Reminder.type` is an open String vocabulary (T060 plan/`reminder.ts` header) -- an unrecognized value falls back to itself rather than throwing. */
function agendaTypeLabel(type: string): string {
  return type in NOTIFICATION_TYPE_LABELS ? NOTIFICATION_TYPE_LABELS[type as ReminderType] : type;
}

const SCHEDULE_FREQ_LABELS: Record<ScheduleFrequency, string> = {
  DAILY: "Daily",
  WEEKLY: "Weekly",
  MONTHLY: "Monthly",
};

export const strings = {
  tabs: {
    home: "Home",
    care: "Care",
    timeline: "Timeline",
    settings: "Settings",
  },
  home: {
    body: "Peace of mind between vet visits — your pet's care, all in one place.",
    openActivePet: "Open pet home",
  },
  switcher: {
    heading: "Your pets",
    switchA11y: "Switch active pet",
  },
  care: {
    body: "Care reminders and templates will live here.",
    setupCta: "Set up a care plan",
    noPet: "Add a pet to set up a care plan.",
  },
  timeline: {
    body: "Your pet's health timeline will live here.",
  },
  settings: {
    body: "Account and household settings will live here.",
    family: "Family",
    notifications: "Notifications",
  },
  auth: {
    welcome: {
      tagline: "Peace of mind between vet visits — sign in to get started.",
      continueWithEmail: "Continue with email",
    },
    email: {
      label: "Email address",
      placeholder: "you@example.com",
      invalidEmail: "Enter a valid email address.",
      submit: "Send code",
      genericError: "Something went wrong. Please try again.",
    },
    otp: {
      prompt: "Enter the 6-digit code we sent you.",
      resend: "Resend code",
      verifying: "Verifying...",
      wrongCode: "That code didn't work. Please try again.",
      genericError: "Something went wrong. Please try again.",
    },
    done: {
      title: "You're all set",
      body: "Your account is ready.",
      continue: "Continue",
    },
    pushRationale: {
      title: "Stay on top of care",
      body: "Turn on notifications so we can remind you about vaccines, meds, and other care reminders.",
      enable: "Enable notifications",
      skip: "Not now",
    },
    social: {
      apple: "Continue with Apple",
      google: "Continue with Google",
      genericError: "Something went wrong. Please try again.",
    },
  },
  addPet: {
    homeCta: "Add a pet",
    common: {
      back: "Back",
      next: "Next",
      skip: "Skip",
      startOver: "Start over",
      stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    },
    species: {
      title: "What kind of pet is this?",
      dog: "Dog",
      cat: "Cat",
    },
    breed: {
      title: "What breed?",
      searchPlaceholder: "Search breeds",
      skip: "Skip — I don't know",
      loading: "Searching breeds…",
      error: "We couldn't load breeds right now.",
      empty: "No matching breeds.",
    },
    details: {
      title: "Tell us about them",
      nameLabel: "Name",
      namePlaceholder: "Your pet's name",
      nameRequired: "Name is required.",
      sexLabel: "Sex",
      male: "Male",
      female: "Female",
      unknown: "Unknown",
      neuteredLabel: "Neutered / spayed",
      birthDateLabel: "Birth date (YYYY-MM-DD)",
      birthDatePlaceholder: "2022-05-01",
      ageEstimateLabel: "Estimated age (months)",
      weightLabel: "Weight (grams)",
      xorError: "Enter either a birth date or an estimated age, not both.",
    },
    photo: {
      title: "Add a photo",
      rationale: "Add a photo so you can recognize your pet at a glance. This is optional.",
      choosePhoto: "Choose photo",
      permissionError: "We couldn't access your photos. You can skip this step.",
      finish: "Finish",
    },
    done: {
      submitting: "Adding your pet…",
      createError: "We couldn't add your pet. Please try again.",
      retry: "Retry",
    },
  },
  petHome: {
    loading: "Loading…",
    error: "We couldn't load this pet.",
    empty: "This pet couldn't be found.",
    done: "Done",
    somethingWrong: "Something wrong?",
    logWeight: "Log weight",
    reminders: "Reminders",
    retry: "Retry",
    offlineBanner: "You're offline — showing your last saved info.",
    offline: "You're offline. Reconnect to load this pet.",
    age: { yr: "yr", mo: "mo", approx: "~", unknown: "Age unknown" },
  },
  comingSoon: {
    title: "Coming soon",
    body: "This part of the app isn't ready yet. Check back soon.",
  },
  check: {
    title: "What's going on?",
    subtitle: "Pick what you've noticed and we'll ask a few quick questions.",
    recentTitle: "Recent checks",
    recentEmpty: "Your recent checks will show up here.",
    recentSeeAll: "See all",
    offlineBanner: "You're offline — you can still start a check.",
    waiting: {
      title: "Looking into it…",
      body: "We're reviewing what you shared. This usually takes a few moments.",
      cancel: "Cancel",
    },
    submit: {
      submitting: "Sending your answers…",
      offlineBlocked: "You're offline. Reconnect to send this check.",
      offlineRetry: "Retry",
      quotaTitle: "You've used your free checks",
      quotaBody:
        "You've reached this month's free symptom checks. You can still reach a vet anytime.",
      quotaUpgrade: "See plans",
      error: "We couldn't send this right now. Please try again.",
      errorRetry: "Retry",
    },
    result: {
      disclaimer: (appName: string) =>
        `${appName} offers general pet-care guidance, not veterinary care or treatment. Always consult a licensed veterinarian.`,
      tierLabel: {
        EMERGENCY_NOW: "Emergency — see a vet now",
        VET_24H: "See a vet within 24 hours",
        VET_SOON: "See a vet soon",
        MONITOR: "Monitor closely at home",
        REASSURE: "Likely not urgent",
      },
      sections: {
        possibleCauses: "What this could be",
        redFlagsToWatch: "When to get help fast",
        homeCare: "Caring for them at home",
        doNot: "What not to do",
        vetQuestions: "Questions to ask your vet",
      },
      fallbackNotice:
        "We couldn't fully assess this from what you shared. When in doubt, it's safest to have a vet take a look.",
      emergencyNoticeTitle: "This may be an emergency",
      emergencyNoticeBody: "Based on what you shared, your pet may need urgent care right away.",
      emergencyNoticeCta: "See emergency steps",
      findVet: "Find a vet nearby",
      share: "Share as text",
      done: "Done",
      loading: "Loading your result…",
      error: "We couldn't load this result.",
      errorHint: "If you're worried about your pet, contact a vet.",
      retry: "Retry",
    },
    emergency: {
      goNowBadge: "Emergency",
      detectedHeading: "What we noticed",
      guidanceHeading: "What to do now",
      hotlineHeading: "Pet poison helpline",
      callHotline: "Call the poison helpline",
      hotlineFallback:
        "We don't have a pet poison helpline listed for your area. If poisoning is possible, contact your nearest emergency vet right away.",
      findVet: "Find an emergency vet",
      acknowledge: "I understand — continue",
    },
    history: {
      title: "Check history",
      empty: "No checks yet. When you run a symptom check, it'll show up here.",
      error: "We couldn't load your check history.",
      retry: "Retry",
      loadMore: "Load more",
      loadingMore: "Loading more…",
      inProgress: "In progress",
      offlineBanner: "You're offline — showing your saved checks.",
      dateA11y: (date: string) => `Checked on ${date}`,
    },
  },
  family: {
    title: "Family",
    loading: "Loading…",
    error: "We couldn't load your household.",
    empty: "We couldn't find your household.",
    retry: "Retry",
    owner: "Owner",
    member: "Member",
    invite: "Invite someone",
    inviteError: "We couldn't create an invite. Please try again.",
  },
  join: {
    title: "Join this household?",
    body: "Accepting will move you into this household and leave your current one.",
    accept: "Join household",
    invalidError: "This invite link is invalid or has expired.",
    petsPresentError:
      "You have pets in your current household. Remove or rehome them before joining another household.",
  },
  notifications: {
    title: "Notifications",
    loading: "Loading…",
    error: "We couldn't load your notification settings.",
    empty: "We couldn't find your notification settings.",
    retry: "Retry",
    offlineBanner: "You're offline — showing your last saved settings.",
    offline: "You're offline. Reconnect to change notification settings.",
    typesHeading: "Care reminder types",
    typeLabel: (type: ReminderType): string => NOTIFICATION_TYPE_LABELS[type],
    quietHours: {
      heading: "Quiet hours",
      enable: "Enable quiet hours",
      body: "We'll hold care reminders during this window and deliver them right after it ends.",
      start: "Start",
      end: "End",
    },
    save: "Save",
    saveError: "We couldn't save your changes. Please try again.",
  },
  carePlan: {
    title: "Set up a care plan",
    subtitle:
      "We've put together a suggested schedule based on your pet's age, species, and region. Review it and adjust anything you like before adding it to your reminders.",
    loading: "Loading…",
    error: "We couldn't load your care plan suggestions.",
    retry: "Retry",
    empty: "No suggestions are available for this pet yet.",
    offline: "You're offline. Reconnect to load care plan suggestions.",
    offlineBanner: "You're offline — showing your last saved suggestions.",
    // The item note itself is rendered verbatim from the resolved
    // care-template data, not from a string here (CLAUDE §7 / plan Safety
    // statement) -- these are labels around it.
    emphasisBadge: "Especially recommended in your region",
    alreadyAddedBadge: "Already added",
    dateEdit: {
      earlier1w: "-1w",
      earlier1d: "-1d",
      later1d: "+1d",
      later1w: "+1w",
    },
    confirm: "Confirm plan",
    skip: "Not now",
    confirmError: "We couldn't save your care plan. Please try again.",
  },
  intake: {
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    back: "Back",
    next: "Next",
    skip: "Skip",
    maxSelectionsHint: (n: number) => `Choose up to ${n}`,
    freeText: {
      title: "Anything else you'd like to add?",
      placeholder: "Add any other details in your own words.",
      optional: "This step is optional.",
    },
    photoStub: "You'll be able to add photos in the next step.",
    photo: {
      title: "Add a photo",
      rationale: "A photo can help us understand what's going on. This step is optional.",
      takePhoto: "Take photo",
      chooseLibrary: "Choose from library",
      permissionError: "We couldn't access your camera or photos. You can skip this step.",
      limitHint: (n: number) => `You can add up to ${n} photos.`,
      retry: "Retry",
      remove: "Remove",
      uploading: (percent: number) => `Uploading ${percent}%`,
      failed: "This photo didn't upload.",
      unavailable: "Photos aren't available right now. You can skip this step.",
    },
    review: { title: "Review your answers", edit: "Edit" },
    submit: "Continue",
    validationError: "Some answers need attention before continuing.",
    invalidCategory: "We couldn't find that category. Go back and pick again.",
    offlineBanner: "You're offline — you can still fill this in.",
  },
  agenda: {
    title: "Care agenda",
    today: "Today",
    upcoming: "Upcoming",
    empty: "No care reminders in this window yet.",
    loading: "Loading…",
    error: "We couldn't load your care agenda.",
    retry: "Retry",
    offline: "You're offline. Reconnect to load your care agenda.",
    offlineBanner: "You're offline — showing your last saved agenda.",
    filterAll: "All",
    markDone: "Mark done",
    snooze: "Snooze",
    newReminder: "+ New reminder",
    carePlanLink: "Set up a care plan",
    statusDone: "Done",
    statusSnoozed: "Snoozed",
    completeError: "We couldn't save that. Please try again.",
    snoozeError: "We couldn't snooze that. Please try again.",
    typeLabel: (type: string): string => agendaTypeLabel(type),
  },
  reminderForm: {
    createTitle: "New reminder",
    editTitle: "Edit reminder",
    typeHeading: "Type",
    titleLabel: "Title",
    titlePlaceholder: "e.g. Rabies booster",
    scheduleHeading: "Schedule",
    freqLabel: (freq: ScheduleFrequency): string => SCHEDULE_FREQ_LABELS[freq],
    intervalLabel: "Every",
    weekdaysLabel: "On these days",
    monthDayLabel: "Day of month",
    startDateLabel: "Start date",
    timeLabel: "Time",
    save: "Save",
    saveError: "We couldn't save this reminder. Please try again.",
    loading: "Loading…",
    error: "We couldn't load this reminder.",
    retry: "Retry",
  },
} as const;
